version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    cooldown:
      default-days: 3
    commit-message:
      prefix: "chore(deps)"
    groups:
      applies-to: "version-updates"
    schedule:
      interval: "cron"
      cronjob: "0 17 * * 0"
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore(deps)"
    cooldown:
      default-days: 2
    schedule:
      interval: "cron"
      cronjob: "0 17 * * 0"
