version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore(deps)"
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    schedule:
      interval: "cron"
      cronjob: "0 17 * * 0"
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore(deps)"
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    cooldown:
      default-days: 7
    schedule:
      interval: "cron"
      cronjob: "0 17 * * 0"
