name: Checks
description: Run checks on push and on pull requests to the main and release branches.

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
      - release/*
    # skip CI for changes that don't affect build or test outcomes
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/dependabot.yml'

permissions: {}

jobs:
  Build_and_check:
    permissions:
      contents: read
      actions: write # required for artifact upload in reusable workflow
    uses: tylerkelly13/.github/.github/workflows/node-run-checks.yml@main
    with:
      node-version: "24.x"
      pnpm-version: "latest"
  
