name: Deploy
description: Deploy the application when a new version is tagged.

on:
  push:
    tags:
      - v*

permissions: {}

jobs:
  Checks:
    permissions:
      contents: read
      actions: write # required for artifact upload in reusable workflow
    uses: tylerkelly13/.github/.github/workflows/node-run-checks.yml@57b7fbaf07c295fe93485f75bcf65449b070794b  # node-run-checks-civ2
    with:
      node-version: "24.x"
      pnpm-version: "latest"

  Release:
    needs: [Checks]
    permissions:
      contents: write # required to create GitHub releases
    uses: tylerkelly13/.github/.github/workflows/node-gh-release.yml@8d7d2e6616254a836736b88f3eb078caf96716db  # node-gh-release-civ1
    with:
      artifact-id: ${{ needs.Checks.outputs.artifact-id }}
