name: Deploy
description: Deploy the application when a new version is tagged.

on:
  push:
    tags:
      - v*

jobs:
  Checks:
    uses: tylerkelly13/.github/.github/workflows/node-run-checks.yml@main
    with:
      node-version: "24.x"
      pnpm-version: "latest"

  Release:
    needs: [Checks]
    permissions:
      contents: write
    uses: tylerkelly13/.github/.github/workflows/node-gh-release.yml@main
    with:
      artifact-id: ${{ needs.Checks.outputs.artifact-id }}
